name: AwesomeChallenges
main: com.emiv.awesomechallenges.Main
version: 1.8.1
commands:
  awesomechallenges:
    aliases: [ac, awesomechallenge]
    description: Command for AwesomeChallenges
  challenge:
    aliases: [challenges, c]
    description: Open challenge menu