name: AwesomeChallenges
main: com.emiv.awesomechallenges.Main
version: 1.5.1
api-version: 1.16
commands:
  awesomechallenges:
    aliases: [ac, awesomechallenge]
    description: Command for AwesomeChallenges
  challenge:
    aliases: [challenges, c]
    description: Open challenge menu